### ISSUE TITLE
Could the code work in pytorch 1.8?

### ISSUE THREAD

**Issue by yunxi1** [IDEA-Research/detrex#123]
I see the main branch works with Pytorch 1.10+ or higher (we recommend Pytorch 1.12). Can it work in pytorch1.8?

**Comment by rentainhe** [comment]
> I see the main branch works with Pytorch 1.10+ or higher (we recommend Pytorch 1.12). Can it work in pytorch1.8?

We use Pytorch 1.10+ because we have implemented [torchvision_backbone](https://github.com/IDEA-Research/detrex/blob/main/detrex/modeling/backbone/torchvision_backbone.py) which needs `feature extractor` function in Torchvision 1.11. If you're not using torchvision backbone, maybe detrex can be correctly runned using Pytorch 1.8.

**Comment by rentainhe** [comment]
As there is no more activity, I am closing the issue~ Feel free to reopen it if necessary. Or you can leave a new issue if you meet some other problems. @yunxi1
