### ISSUE TITLE
LVIS Pretrained Models

### ISSUE THREAD

**Issue by mmaaz60** [IDEA-Research/detrex#292]
Hi Authors,

Thank you for the great effort. Any plans to including LVIS models in the model zoo? Further, is it possible to use the LVIS models from the parent directory in this repo (e.g. the EVA-02 model from https://huggingface.co/Yuxin-CV/EVA-02/blob/main/eva02/det/eva02_L_lvis_sys_o365.pth.

Thanks

**Comment by rentainhe** [comment]
> Hi Authors,
> 
> Thank you for the great effort. Any plans to including LVIS models in the model zoo? Further, is it possible to use the LVIS models from the parent directory in this repo (e.g. the EVA-02 model from https://huggingface.co/Yuxin-CV/EVA-02/blob/main/eva02/det/eva02_L_lvis_sys_o365.pth.
> 
> Thanks

You can directly train the model under LVIS dataset by slightly updating the config file, because detectron2 has defaultly supported LVIS dataset training and evaluation.

More details can be found in detectron2's official documentation.

And both detrex and EVA were built upon detectron2, so you can easily adopt EVA models in detrex I think

**Comment by rentainhe** [comment]
I'm going to close this issue now, feel free to reopen it if needed
